name: CalorieTracker

configs:
  App-Store: release
  Debug: debug

options:
  bundleIdPrefix: com.BroadApps
  deploymentTarget: 14.0
  groupSortPosition: top
  developmentLanguage: en
  createIntermediateGroups: true
packages:
    Alamofire:
      url: https://github.com/Alamofire/Alamofire.git
      majorVersion: 5.6.1
    SnapKit:
      url: https://github.com/SnapKit/SnapKit.git
      majorVersion: 5.0.1
    Gzip:
      url: https://github.com/1024jp/GzipSwift.git
      majorVersion: 5.2.0
    Kingfisher:
      url: https://github.com/onevcat/Kingfisher.git
      majorVersion: 7.6.0
    Lottie:
      url: https://github.com/airbnb/lottie-ios.git
      majorVersion: 3.0.0
    Swinject:
      url: https://github.com/Swinject/Swinject.git
      majorVersion: 2.8.0
targets:
  CalorieTracker:
    devices: [iPhone]
    type: application
    platform: iOS
    deploymentTarget: 14.0
    # info:
    #   path: CalorieTracker/Info.plist
    #   properties:
    #     UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    #     UILaunchStoryboardName: LaunchScreen

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: DWARF with dSYM File
      # INFOPLIST_FILE:
    dependencies:
      - package: SnapKit    
      - package: Gzip
      - package: Kingfisher
      - package: Lottie
      - package: Swinject
      - package: Alamofire
    sources:
       - path: ./CalorieTracker
    preBuildScripts:
      - script: |
            "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint
      - script: |
            if [ $ACTION != "indexbuild" ]; then
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/$TARGET_NAME/Sources/Generated/R.generated.swift"
            fi
        name: "R.Swift"
        basedOnDependencyAnalysis: false
        outputFiles:
          - $SRCROOT/$TARGET_NAME/Sources/Generated/R.generated.swift
    postBuildScripts:
      - script: |
              "${PODS_ROOT}/FirebaseCrashlytics/run"
        name: "Crashlytics"
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
schemes:
  App-Store:
    build:
      targets:
        CalorieTracker: all
    run:
      config: App-Store
  Debug:
    build:
      targets:
        CalorieTracker: all
    run:
      config: Debug
